* Introduction


Way back in the mists of time, browser bookmarks and favourites were
stored in directory structures as individual files (e.g. with a ".url"
extension).  They could be managed and searched just like any other
files. Now they tend to be stored in sqlite and exported into html or
json. This program can convert any of these formats (back) into a file
hierarchy.

 Convert bookmarks/favorites from source format (html, json, or sqlite)
 and create corresponding nested folders and files by depth-first-traversal ("dft")
 - file name is bookmark simplified name, with ".url" as extension
 - inside the file are the bookmark details:
     - the exact name ('title') of the bookmark
     - dates (added,modified,last_visited)
     - any other details
 - bookmark last_visited date is used to set modification of file name
   so that tools like "find" can be used (e.g. find ./ -name '*foo*' -mtime +100 )



* Installing
 
no installer just code


* Usage: bookmark_merger.py [options] dir_path1 dir_path2

All html files in the given directories will be assumed to be firefox
bookmark.html files.
If no directory is given then the current directory will be used

Options:
  -h, --help            show this help message and exit
  -r, --recursive       Recursively explore given directory for bookmark files
  -o FILE, --outfile=FILE
                        write output to FILE [default: merged bookmarks.html]


* Description 
--------------------

This is a python library/module written mostly for the purpose of merging multiple bookmark files together. It works only with the bookmark.html files created by firefox (although possibly netscape would use the same files?). Rather than removing all duplicate hyperlinks, it works with the folder structure of the bookmarks; merging together two bookmark files in the same way that two recursive filesystem directories would be combined. Folders with the same name are merged appropriately with the removal of duplicate entries and the merging of entries with the same hyperlink but different strings (see the function - merge_entries).

The library consists of two parts. The first is a parsing grammar defined using the 'pyparsing library'. This turns a bookmark file into a recursive collection of strings along with some named attributes consisting of folder name and lists of found hyperlinks. The pyparsing module documentation should be consulted to understand the pyparsing.parseResults class. Optionally the original string can be recreated from the parseResults instance (see function -serialize).

The second part is a set of functions for creating a recursive set of dictionaries and for merging two or more bookmark files together.

The module is expected to be used at the python shell or in a script. The example script - 'example.py' - shows high level use.


Main Functions & Objects
-------------------------

bookmarkshtml - a pyparsing grammar. Use via 


See Also

bookmark_merger.py


TO DO
-----

Devide the module into two; (1) the pyparsing grammar and (2) the 'bookmarkDict' functions
